### ISSUE TITLE
IE8 javascript bug

### ISSUE THREAD

**Issue by walterfaas** [zeusdeux/isInViewport#13]
Hi, the script gives errors on IE8, even on the demo page. See image attached.
![screen shot 2014-11-25 at 11 02 54](https://cloud.githubusercontent.com/assets/3436264/5181022/aba1cbc2-7492-11e4-8be1-ba5b56324e01.png)

**Comment by zeusdeux** [comment]
Fixed in @44caa2ec19e568b7e57be4bc8ed2201e2ab1f166

Thanks for the report.
