### ISSUE TITLE
Determine when an element is no longer in the viewport and chain a function to it

### ISSUE THREAD

**Issue by EricJammin** [zeusdeux/isInViewport#17]
I'm not sure if this type of functionality exists within the plugin, but I am looking a for a way to determine when a specific element is no longer in the viewport, and chain a function to that as well. For example:

$('#elementA:in-viewport').do(function(){
    $('#elementB').addClass('hidden');
 });

That works just fine. Now, I'm looking for a method so that when elementA is no longer in the viewport, I can remove that class from elementB.

Apologies if I am overlooking something simple. Thanks.

**Comment by zeusdeux** [comment]
There isn't baked in functionality for that but it is quite easily doable.

When `#elementA` isn't in viewport, the length of the array returned by `$('#elementA:in-viewport')` will be zero. You can use that in an `if` block and do your bidding there.

Here's the code:
```javascript
if (!$('#elementA:in-viewport').length) {
  $('#elementB').removeClass('hidden');
}
```

I know it isn't pretty and this makes me wonder if I should expose `isInViewport` as a function again (it used to be that way in the older version before it was deprecated in favour of the the custom `:in-viewport` selector).

**Comment by EricJammin** [comment]
Ah, I remember the older version where it was exposed, I was wondering if there was still any possibilities with that.

But, the code you gave does work perfectly for my needs. Thank you very much! I'll keep watching to see what future updates hold.

**Comment by zeusdeux** [comment]
@EricJammin no problem. Glad I could help.

Also, your use case is fairly common. Let me come up with a clean way of handling that within the plugin itself. And if all else fails, I'll probably just expose `isInViewport` method again.

Oh and do let me know if I can close this. :)

**Comment by EricJammin** [comment]
That sounds great! Yes, please feel free to close this.
