### ISSUE TITLE
Support .is() selector

### ISSUE THREAD

**Issue by justrhysism** [zeusdeux/isInViewport#18]
I regularly cache my jQuery elements early:

```javascript
var $myElem = $('#my-elem');
```

It would be super handy if I could use this plugin like:

```javascript
if ($myElem.is(':in-viewport')) {
  // do stuff...
}
```

**Comment by zeusdeux** [comment]
It does work with `.is` already.
Here's a [demo](http://codepen.io/zeusdeux/pen/emVoPK).

What version of jQuery are you on?

**Comment by justrhysism** [comment]
I ended up not needing to use it that way when I was refactoring.

However it might be worth adding that usage to your documentation (and closing this issue) :).
