### ISSUE TITLE
Demo - 404

### ISSUE THREAD

**Issue by vistar** [zeusdeux/isInViewport#20]
http://experiments.muditameta.com/isInViewport/

**Comment by blakeperdue** [comment]
Any update on getting moved to a new provider? Would be great to have a live demo somewhere linkable.

**Comment by sebastiansulinski** [comment]
yep 404

**Comment by zeusdeux** [comment]
@vistar @blakeperdue @sebastiansulinski The demo should now be back up [here](http://isinviewport.mudit.xyz).

Sorry this took a while.

**Comment by blakeperdue** [comment]
Awesome, thanks @zeusdeux

**Comment by sebastiansulinski** [comment]
Thanks @zeusdeux
