### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by ixlipixli** [zeusdeux/isInViewport#21]
Hi,
I am using your script to control the autoplay of a video.
The sites has a slider with several slides. The slides consist of a fullscreen image followed by the content. On one slide I am having the video that should autoplay as soons as the user scrolls the according slide down. (The slides are set to "display block" or "display none".

Is your script able to help me out here because right now it's not working?

**Comment by zeusdeux** [comment]
Could you paste some code here for me to review @ixlipixli?

Thanks.

**Comment by zeusdeux** [comment]
Since there hasn't been any activity on this for about 9 months now, going to assume the issue was resolved. Closing.
