### ISSUE TITLE
using jquery selector

### ISSUE THREAD

**Issue by baraamashaal** [zeusdeux/isInViewport#22]
hi
i have this variable
```
var activates = $('#notification');
```
and it is an `ul` having scroll-able `li` items and i want to target what is appear on `ul` view ?  (it has max-width) okay !

that is worked perfectly with me
```
activates.children('li:in-viewport( 0, #notification )');
``` 
i want to use my variable `activates` in this selector `('li:in-viewport( 0, #notification )` i want to replace  `#notification` with my variable `activates`;

why i have to target the viewport again and find it from the begging in the DOM  and i have already done !! 

sorry for my bad english

**Comment by zeusdeux** [comment]
Hey @baraamashaal, sadly the params to the `in-viewport` selector are all strings and hence you can't pass the reference that you already have stored in a variable to the `in-viewport` selector. It's a limitation at the jquery level.

**Comment by zeusdeux** [comment]
So, I went back and made a few changes to accommodate your use case @baraamashaal.

I have exposed a saner version of `isInViewport` as a chainable function.

You can now do:

```javascript
var activates = $('#notification');

activates.children('li').isInViewport({ viewport: activates });
```

The documentation for it is [here](https://github.com/zeusdeux/isInViewport#using-exposed-isinviewport-function).

**Comment by baraamashaal** [comment]
@zeusdeux thank u  I really appreciate it :smile:

**Comment by zeusdeux** [comment]
@baraamashaal No problem. :+1: 

Closing this issue.
