### ISSUE TITLE
Dumb NPM question

### ISSUE THREAD

**Issue by donpinkus** [zeusdeux/isInViewport#31]
Great library, but how do I use this with jquery required by NPM?

For example:

myFile.js
```
import $ from 'jquery';
import isInViewport from 'is-in-viewport';

// Throws an error: 
// Uncaught ReferenceError: jQuery is not defined(…) isInViewport.js:182 
```

**Comment by zachcowell** [comment]
I am also experiencing this issue. @donpinkus did you find a solution?

**Comment by zeusdeux** [comment]
@donpinkus @zachcowell Not a dumb question at all. Support for this will be out soon.
You can preview it [on the `dev` branch](https://github.com/zeusdeux/isInViewport/blob/dev/src/index.js) currently. 

You will be able to then just do `import 'is-in-viewport'`.
It doesn't export anything as it only side-effects the `jquery` import.

**Comment by zeusdeux** [comment]
@donpinkus @zachcowell I just published v3.0.0 of `is-in-viewport`. Bundling should now work.
Documentation on using in a module [can be found here](https://github.com/zeusdeux/isInViewport/tree/master/examples/es6-example).

**Comment by zeusdeux** [comment]
Gonna close this. Feel free to reopen or open a new issue if bundling still doesn't work. Cheers!

**Comment by donpinkus** [comment]
thanks @zeusdeux!
