### ISSUE TITLE
Demos in Download not working

### ISSUE THREAD

**Issue by Dreamfish19** [zeusdeux/isInViewport#32]
Hi,

the demos in the downloadable zip Archive are not working, neither in Chrome 54 nor in Firefox 50 on Windows 10.

The console is throwing the following error:

SyntaxError: expected expression, got '.'[Weitere Informationen]  isInViewport.js:1
uncaught exception: Syntax error, unrecognized expression: in-viewport

**Comment by zeusdeux** [comment]
Hey @Dreamfish19! Could you try downloading the zip now, running an http server in the root directory (not in the examples dir) and checking if things work fine?

I just released a new version with a bunch of fixes and updates.

**Comment by zeusdeux** [comment]
Closing this as there's hasn't been any activity on this for a few months. Feel free to reopen if you're still having troubles. Thanks!
