### ISSUE TITLE
e.not(':in-viewport') doesn't seem to work

### ISSUE THREAD

**Issue by petski** [zeusdeux/isInViewport#34]
`e.not(':in-viewport')` doesn't seem to work.

As a workaround I use `if(! e.is(':in-viewport')) ...`

**Comment by zeusdeux** [comment]
This works as far as my testing goes. Could you gimme a test case that reproduces this please?

**Comment by petski** [comment]
I made a really stupid mistake.... [1]. Sorry for bothering! 

jQuery's `.not()` is not the opposite of `.is()`. The first returns a jQuery object, the second returns a boolean.

See https://jsfiddle.net/petski/y27he9mr/ for my test-cases, assuming that `#in` is in the viewport and `#out` is not:

```
A: $('#in').is(':in-viewport') == true
B: $('#out').not(':in-viewport') == [object Object]
C: $('#out').not(':in-viewport').length > 0 == true
D: ! $('#out').is(':in-viewport') == true
```

[1] In my defense, Feb 10th was on a Friday :)

**Comment by zeusdeux** [comment]
@petski gotcha. No worries!
