### ISSUE TITLE
Add jQuery alias support

### ISSUE THREAD

**Issue by ivankayzer** [zeusdeux/isInViewport#38]
Sometimes the dollar sign ($) is already used by another library (Prototype, MooTools) and it is impossible to use your plugin. Would be great to add the support for jQuery alias for it. 

Thank you.

**Comment by ivankayzer** [comment]
Oh, I can use this instead.

```js
(function($) {})(jQuery);
```

Sorry :)

**Comment by zeusdeux** [comment]
@ivankayzer This should be fixed in `3.0.1`
