### ISSUE TITLE
JS error Cannot use 'in' operator to search for 'default' in undefined

### ISSUE THREAD

**Issue by sylvainbaronnet** [zeusdeux/isInViewport#39]
Hello,

Using `lib/isInViewport.min.js` I have this error in Chrome or Firefox.

Should I use babel or something now ?

`Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined`

**Comment by sylvainbaronnet** [comment]
It happend when you load jQuery in noConflict mode

**Comment by iceteabottle** [comment]
Quick and dirty fix: 
```
// fix jquery in noConflict mode
// $ = 'default' in $ ? $['default'] : $; // comment this out 
$ = jQuery; // add this line below
```

**Comment by sven-ra** [comment]
will there be an official fix for this?

**Comment by zeusdeux** [comment]
@sven-ra @sylvainbaronnet @iceteabottle This should now be fixed! Thanks for the report and workaround! ^_^
