### ISSUE TITLE
Has anyone been able to get this to work with a horizontal scrolling page?

### ISSUE THREAD

**Issue by ThomasMW** [zeusdeux/isInViewport#45]
As the title states. I have a one page which scrolls horizontally and I'm trying to play / pause HTML5 videos when they are in / out of the viewport.

No luck so far, anyone else?

**Comment by zeusdeux** [comment]
You can see that it work in 4th div in the [advanced example](https://isinviewport.mudit.xyz/advanced-viewport.html).
