### ISSUE TITLE
Delay before play() and after pause() method

### ISSUE THREAD

**Issue by SanchezAlex** [zeusdeux/isInViewport#47]
How I can add delay (2s for example) before play() and after pause() method?

$(window).scroll(function() {
    $('#video').each(function(){
        if ($(this).is(":in-viewport")) {
            $(this)[0].play();

        } else {
            $(this)[0].pause();
        }
    })
});

**Comment by zeusdeux** [comment]
`setTimeout` maybe? This question is not specific to this plugin. More of general javascript. Closing.
