### ISSUE TITLE
Look for an example with if and is and tolerance

### ISSUE THREAD

**Issue by derSteffen** [zeusdeux/isInViewport#48]
Hello,

I want to use the in-viweport with selector and toleranance but from the bottom of the page

```
if ( $('.mydiv').is( ':in-viewport(300)') ) {
	alert('yes');
	}
```

Thanks for your help!

Greeteings

**Comment by zeusdeux** [comment]
A [negative tolerance](https://github.com/zeusdeux/isInViewport#example-1) is what you need for this.
