### ISSUE TITLE
Is there an opinion for next class-selectors?

### ISSUE THREAD

**Issue by derSteffen** [zeusdeux/isInViewport#49]
Hello,

I have div with the class="xyz". Now I want say if xyz in the viewport "scroll to the article-div". For the first action, if the first xyz is in the viewport everything is fine.
But then it scroll to the next articel-div without the request "if xyz in the viewport". 

Is it possible to remove the class from the xyz which is it any more in the viewport and then use the next xyz-div for the request.

Thanks very much!

Greetings

**Comment by zeusdeux** [comment]
Hey! Is there any code I could look at as I don't understand the question quite clearly?

**Comment by zeusdeux** [comment]
Closing this as it's been open with no response for 2y now. Feel free to reopen!
