### ISSUE TITLE
Check element is within the viewport when scroll up or down

### ISSUE THREAD

**Issue by josecao** [zeusdeux/isInViewport#51]
Hi author,

I want to check element has within the window for scroll up or down. But i see it detect for up. 

Could you help me ?

Thanks.

**Comment by zeusdeux** [comment]
Hi! 
Do you mean you want to know the direction in which the element came into or left the viewport?

**Comment by zeusdeux** [comment]
Closing this as it's been open with no response for >1y now. Feel free to reopen!
