### ISSUE TITLE
IE11 not detecting view-detect

### ISSUE THREAD

**Issue by elliottmangham** [zeusdeux/isInViewport#52]
Hi,

We added view detect to the site below and it is working perfectly in modern browsers, although I noticed that it isn't working on IE11:
https://infinityworks.com/

The DOM element that it is added to is `header.home-hero` which is the large hero you first see. On IE11, the `in-view viewed` classes have not been applied.

I have tried also including the [IntersectionObserver](https://github.com/w3c/IntersectionObserver) script before jQuery, but that does not seem to have any effect.

Do you have any suggestions?

Thank you and warmest regards,
Elliott

**Comment by elliottmangham** [comment]
Apologies, the issue was a conflict of another plugin.

**Comment by zeusdeux** [comment]
No worries at all! Thank you for closing this!

**Comment by zeusdeux** [comment]
If you can outline the conflict, it would be useful for others so please feel free to do so.
